default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

development:
  <<: *default
  database: myapp_development
  username: luis
  password: luis123

test:
  <<: *default
  database: myapp_test
  username: luis
  password: luis123

production:
  <<: *default
